### ISSUE TITLE
Image based Subs broken

### ISSUE THREAD

**Issue by spike1478** [poly-tonal/VideoConverter#1]
Issue: When image based subtitles are unable to be converted to subrip the script gives up at 0kb for the converted file but still deletes the orginal file
To Replicate:  Run the script on a folder that contains a video file that contains a image based subtitle such as dvdsub.

Specs:

Processor	Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz   2.30 GHz
Installed RAM	8.00 GB (7.85 GB usable)

**Comment by poly-tonal** [comment]
Added a line to handle dvb_subtitle formatted subtitles by default in the codec filtering - also added protections to the deletion so it should only be able to do that when the new file exists.
